### ISSUE TITLE
Close source this repo?

### ISSUE THREAD

**Issue by jturnbull** [incuna/incuna-sass#38]
This repo is open source, but doesn't seem to offer any community benefit. Would anyone use this outside of Incuna projects? 

It also contains various mentions of ePatient and its functionality. Nothing too concerning, but we would need to be more careful if there's a good reason to keep it open.

cc @incuna/frontend

**Comment by perry** [comment]
Yes :-)

**Comment by jturnbull** [comment]
IRL discussion led to a decision to move the ePatient stuff out of here, and documenting what is left. Any objections?

**Comment by perry** [comment]
Nope. Should be all contained to [this dir](https://github.com/incuna/incuna-sass/tree/master/incuna-sass/projects/epatient/modules).

**Comment by jturnbull** [comment]
Cool, thanks

**Comment by henrahmagix** [comment]
None from me

On 10 June 2015 at 17:20, James Turnbull <notifications@github.com> wrote:

> IRL discussion led to a decision to move the ePatient stuff out of here,
> and documenting what is left. Any objections?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/incuna/incuna-sass/issues/38#issuecomment-110820405>.
>



-- 
Henry Blyth - Developer
henry@incuna.com
01865 791 494
Incuna Ltd, 16 Middle Way, Oxford, OX2 7LH

**Comment by grahamgilchrist** [comment]
I think there are some very useful general sass mixins in here, which can be of use to the wider community. Especially some of the cross browser standardisation mixins.

However, I definitely think it needs some TLC and considering our desire to move away from compass, some re-working.

These would be my suggestions for the future of the project:
* Split the project into `incuna-sass` and `incuna-compass`, which would ease the transition out of compass and leave the `incuna-sass` parts easily used by other sass implementations like node-sass
* split the ePatient styles to another project. Either `incuna-epatient-sass` which cold be closed source, or possibly keeping and versioning them with the ePatient templates
* Documentation. Much better documentation on the available mixins, what they do, why they are needed, how you start a project etc.

**Comment by grahamgilchrist** [comment]
Done in #50
