### ISSUE TITLE
Fine tuning

### ISSUE THREAD

**Issue by hippogriffic** [incuna/incuna-sass#45]
@incuna/frontend can we have a discussion about this library? I'd like to get it de-compassed so we can stop slowing our grunt down so much and generally tidy it up / make it better / more useful.

So I know that @grahamgilchrist has suggested splitting it into 2 libraries, one with compass, one without. Thoughts about that? How do we go about it?

From what I can see not too much of this is using compass. Obviously sprites but we're working on a solution to that. The only other things I can see are a couple of instances of `@include background-size` (is that necessary anymore?). And some stuff in `modal.sass`. Am I missing anything?

Also I'm not convinced that everything in here is necessary, so a good first step would be to remove anything we no longer feel is useful. For example I think the `inline-block` and `box-sizing` helpers can go, there's no reason for them that I can see, both of those things are pretty widely supported now. (also getting rid of `box-sizing` would bring us one step closer to getting rid of compass). Does anybody disagree? Can anything else be removed?

There's also a lot of stuff in here that I either don't understand or can't see the purpose of. So it would be good to get some use cases for when these things might be helpful and some documentation for how they could be used. And possibly some of these things aren't necessary? I don't know.
Here's my list:
- [ ] `visually-hidden`
- [ ] `vertical-center`
- [ ] `overflow-scroll`
- [ ] `image-replace`
- [ ] `icomoon` (I think this is an iconfont thing, do we want to be supporting this still?)
- [ ] `clearfix` (I know we use this, I've used it, but I don't understand why it's better than `clear:`)
- [ ] `messages` (I can't really tell what this is intended to be used for)

So let's discuss these things and their purpose and maybe we can (between us :D) get some documentation into the files.

And feel free to add to the list. I made checkboxes so we can check them off as we make decisions :)

**Comment by henrahmagix** [comment]
I'm keen to split out Compass-specific things into `incuna-compass`. Then this library will match it's name: Sass-only.

**Comment by grahamgilchrist** [comment]
Yes, my original idea, to more easily stage the transition form compass was to move the compass-specific things to `incuna-compass`.

This will consist of (off the top of my head):
* sprites
* image-width /image-height
* browser support variables in mixins
* compass CSS3 use (although this can be replaced with (https://github.com/Igosuki/compass-mixins)

**Comment by grahamgilchrist** [comment]
The helpers/mixins could definitely do with some docs 

*  `inline-block` basically here for backwards compatibility with <IE7/IE8. Increasingly we don't need to target these browsers, but until we drop them completely, it's useful to keep
* `box-sizing` appears to just be a conversion of the compass `box-sizing` mixin to a sass extension. This is mostly for CSS efficiency I think
* `visually-hidden` I think this is a recommended accessible way to hide text
* `vertical-center` This I think is an attempt to make a foolproof vertical center assistant
* overflow-scroll
 image-replace
 icomoon (I think this is an iconfont thing, do we want to be supporting this still?)
 clearfix (I know we use this, I've used it, but I don't understand why it's better than clear:)
 messages (I can't really tell what this is intended to be used for)

I agree we should look and re-evaluate these.

**Comment by maciejpi** [comment]
yeah, I agree that we should clean it up a bit. and provide better docs:)

**Comment by hippogriffic** [comment]
this has been move to other issues
