### ISSUE TITLE
Replacing compass mixins

### ISSUE THREAD

**Issue by hippogriffic** [incuna/incuna-sass#52]
We are using several compass mixins in this library that we need to replace with something else so we can continue to support the files.

I have made new `box-sizing` helpers to replace the compass reliant ones we had before in #51. Will these suffice? We could easily make a mixin to do the same thing...

In #51 I also replaced all instances of `@extend %inline-block` with `display: inline-block`

These are the remaining compass reliant mixins that I found in the library:

- [x] `border-radius`
- [x] `box-shadow`
- [x] `transition` (this one had several varieties with different suffixes)
- [x] `translate`

so do we want to write our own mixins to replace these? Or use another library, like bourbon?

@incuna/frontend discuss

**Comment by pandalion** [comment]
I think for `border-radius`, we should be okay to just use the property as it is. It's supported by pretty much everything now without vendor prefixes. IE8 and Opera Mini don't support it and for those we can fall back to just normal borders. Since border-radius is purely a decorative enhancing thing, I don't think we need a mixin for it anymore.

**Comment by hippogriffic** [comment]
@pandalion I would like to have a mixin even if it's just for the purpose of being able to shorthand `border-top-radius` or `border-left-radius` because I can never remember which order they should go in and it's confusing if you have different values for each corner. But that should be something we can make ourselves

**Comment by pandalion** [comment]
@hippogriffic Do we need a replacement for gradient backgrounds too, eg `@include background`

**Comment by hippogriffic** [comment]
ah yes, probably, I think I just listed the ones from incuna-sass here but we should put everything we need to replace. Feel free to add to the list :)

**Comment by grahamgilchrist** [comment]
I don't think we should be maintaining our own versions of mixins that are readily available in open source projects.

For the CSS3 vendor-prefix mixins, the ones in compass-mixins or bourbon should suffice?
* https://github.com/Igosuki/compass-mixins
* http://bourbon.io/docs/

**Comment by pandalion** [comment]
After discussion yesterday it looks like using node-bourbon will be the best thing https://www.npmjs.com/package/node-bourbon

**Comment by hippogriffic** [comment]
the only one of these that isn't in compass is box-shadow, do we need a mixin for that? It looks like it's pretty well supported

**Comment by maciejpi** [comment]
@hippogriffic  I''d say, only for legacy project.

**Comment by hippogriffic** [comment]
I don't think we need a box-shadow mixin, closing this issue
